# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('eslogan', models.CharField(blank=True, max_length=600, null=True)),
                ('imagen_logo', models.CharField(blank=True, max_length=3600, null=True)),
                ('video', models.CharField(blank=True, max_length=3600, null=True)),
                ('mision', models.CharField(blank=True, max_length=2000, null=True)),
                ('vision', models.CharField(blank=True, max_length=2000, null=True)),
                ('acerca', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bit', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bitacora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('usuario_id_admin', models.BigIntegerField(blank=True, null=True)),
                ('usuario_id_user', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id_elemento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('data', models.CharField(blank=True, max_length=3600, null=True)),
                ('permisos', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'elemento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.BigIntegerField(primary_key=True, serialize=False)),
                ('emisor', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'mensaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=600, null=True)),
                ('clave', models.CharField(blank=True, max_length=32, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.CharField(blank=True, max_length=3600, null=True)),
                ('genero', models.CharField(blank=True, max_length=40, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('status_cuenta', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usuario_grupo',
                'managed': False,
            },
        ),
    ]
